name: Release Management

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release_workflow

jobs:
  build_and_upload:
    name: Build SU2
    strategy:
      fail-fast: false
      matrix:
        os_bin: [macos, linux]
        include: 
          - os_bin: macos
            flags: '-Dwith-mpi=disabled --cross-file=/hostfile_darwin'
          - os_bin: linux
            flags: '-Dwith-mpi=disabled'
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: talbring/jenkins-release-drafter@v5.2.0-jenkins-6
        name: Update Release
        id: update_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker://su2code/build-su2-darwin:latest
        with:
          args: -b develop -f "${{matrix.flags}}"
      - name: Create Archive
        run: |
          cd install
          zip -r ${{matrix.os_bin}}.zip bin      
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.update_release.outputs.uploadurl }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: install/${{matrix.os_bin}}.zip
          asset_name: install/${{matrix.os_bin}}.zip
          asset_content_type: application/zip
