name: Release Management

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release_workflow

jobs:
  build_and_upload:
    name: Build SU2
    strategy:
      fail-fast: false
      matrix:
        os_bin: [macos, linux]
        include: 
          - os_bin: macos
            flags: '-Dwith-mpi=false --cross-file=/hostfile_darwin'
          - os_bin: linux
            flags: '-Dwith-mpi=false'
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: talbring/jenkins-release-drafter@v5.2.0-jenkins-6
        name: Update Release
        id: update_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Assests
        run: |
          echo ${{ steps.update_release.outputs.uploadurl }}
